@base_url = https://localhost:7015/api/categoria

### Listar Categorias ###
GET {{base_url}}/listar

### Criar Categoria ###
POST {{base_url}}/cadastrar
Content-Type: application/json

{
    "nome": "Dormir"
}
